/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package io.github.walker_tx.esv.operations;

import static io.github.walker_tx.esv.operations.Operations.RequestOperation;
import static io.github.walker_tx.esv.operations.Operations.AsyncRequestOperation;

import com.fasterxml.jackson.core.type.TypeReference;
import io.github.walker_tx.esv.SDKConfiguration;
import io.github.walker_tx.esv.SecuritySource;
import io.github.walker_tx.esv.models.errors.APIException;
import io.github.walker_tx.esv.models.errors.Error;
import io.github.walker_tx.esv.models.operations.GetPassageAudioRequest;
import io.github.walker_tx.esv.models.operations.GetPassageAudioResponse;
import io.github.walker_tx.esv.utils.Blob;
import io.github.walker_tx.esv.utils.Exceptions;
import io.github.walker_tx.esv.utils.HTTPClient;
import io.github.walker_tx.esv.utils.HTTPRequest;
import io.github.walker_tx.esv.utils.Hook.AfterErrorContextImpl;
import io.github.walker_tx.esv.utils.Hook.AfterSuccessContextImpl;
import io.github.walker_tx.esv.utils.Hook.BeforeRequestContextImpl;
import io.github.walker_tx.esv.utils.Utils;
import java.io.InputStream;
import java.lang.Exception;
import java.lang.RuntimeException;
import java.lang.String;
import java.lang.Throwable;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import java.util.function.Function;


public class GetPassageAudio {

    static abstract class Base {
        final SDKConfiguration sdkConfiguration;
        final String baseUrl;
        final SecuritySource securitySource;
        final HTTPClient client;

        public Base(SDKConfiguration sdkConfiguration) {
            this.sdkConfiguration = sdkConfiguration;
            this.baseUrl = this.sdkConfiguration.serverUrl();
            this.securitySource = this.sdkConfiguration.securitySource();
            this.client = this.sdkConfiguration.client();
        }

        Optional<SecuritySource> securitySource() {
            return Optional.ofNullable(this.securitySource);
        }

        BeforeRequestContextImpl createBeforeRequestContext() {
            return new BeforeRequestContextImpl(
                    this.sdkConfiguration,
                    this.baseUrl,
                    "getPassageAudio",
                    java.util.Optional.of(java.util.List.of()),
                    securitySource());
        }

        AfterSuccessContextImpl createAfterSuccessContext() {
            return new AfterSuccessContextImpl(
                    this.sdkConfiguration,
                    this.baseUrl,
                    "getPassageAudio",
                    java.util.Optional.of(java.util.List.of()),
                    securitySource());
        }

        AfterErrorContextImpl createAfterErrorContext() {
            return new AfterErrorContextImpl(
                    this.sdkConfiguration,
                    this.baseUrl,
                    "getPassageAudio",
                    java.util.Optional.of(java.util.List.of()),
                    securitySource());
        }
        <T>HttpRequest buildRequest(T request, Class<T> klass) throws Exception {
            String url = Utils.generateURL(
                    this.baseUrl,
                    "/passage/audio/");
            HTTPRequest req = new HTTPRequest(url, "GET");
            req.addHeader("Accept", "audio/mpeg")
                    .addHeader("user-agent", SDKConfiguration.USER_AGENT);

            req.addQueryParams(Utils.getQueryParams(
                    klass,
                    request,
                    null));
            Utils.configureSecurity(req, this.sdkConfiguration.securitySource().getSecurity());

            return req.build();
        }
    }

    public static class Sync extends Base
            implements RequestOperation<GetPassageAudioRequest, GetPassageAudioResponse> {
        public Sync(SDKConfiguration sdkConfiguration) {
            super(sdkConfiguration);
        }

        private HttpRequest onBuildRequest(GetPassageAudioRequest request) throws Exception {
            HttpRequest req = buildRequest(request, GetPassageAudioRequest.class);
            return sdkConfiguration.hooks().beforeRequest(createBeforeRequestContext(), req);
        }

        private HttpResponse<InputStream> onError(HttpResponse<InputStream> response, Exception error) throws Exception {
            return sdkConfiguration.hooks().afterError(
                    createAfterErrorContext(),
                    Optional.ofNullable(response),
                    Optional.ofNullable(error));
        }

        private HttpResponse<InputStream> onSuccess(HttpResponse<InputStream> response) throws Exception {
            return sdkConfiguration.hooks().afterSuccess(createAfterSuccessContext(), response);
        }

        @Override
        public HttpResponse<InputStream> doRequest(GetPassageAudioRequest request) throws Exception {
            HttpRequest r = onBuildRequest(request);
            HttpResponse<InputStream> httpRes;
            try {
                httpRes = client.send(r);
                if (Utils.statusCodeMatches(httpRes.statusCode(), "400", "401", "4XX", "5XX")) {
                    httpRes = onError(httpRes, null);
                } else {
                    httpRes = onSuccess(httpRes);
                }
            } catch (Exception e) {
                httpRes = onError(null, e);
            }

            return httpRes;
        }


        @Override
        public GetPassageAudioResponse handleResponse(HttpResponse<InputStream> response) throws Exception {
            String contentType = response
                    .headers()
                    .firstValue("Content-Type")
                    .orElse("application/octet-stream");
            GetPassageAudioResponse.Builder resBuilder =
                    GetPassageAudioResponse
                            .builder()
                            .contentType(contentType)
                            .statusCode(response.statusCode())
                            .rawResponse(response);
            if (Utils.statusCodeMatches(response.statusCode(), "200") && Utils.contentTypeMatches(contentType, "audio/mpeg")) {
                resBuilder.responseStream(response.body());
            }

            GetPassageAudioResponse res = resBuilder.build();
            
            if (Utils.statusCodeMatches(response.statusCode(), "200")) {
                if (Utils.contentTypeMatches(contentType, "audio/mpeg")) {
                    return res;
                } else {
                    throw new APIException(
                            response,
                            response.statusCode(),
                            "Unexpected content-type received: " + contentType,
                            Utils.extractByteArrayFromBody(response));
                }
            }
            
            if (Utils.statusCodeMatches(response.statusCode(), "400", "401")) {
                if (Utils.contentTypeMatches(contentType, "application/json")) {
                    Error out = Utils.mapper().readValue(
                            response.body(),
                            new TypeReference<>() {
                            });
                    throw out;
                } else {
                    throw new APIException(
                            response,
                            response.statusCode(),
                            "Unexpected content-type received: " + contentType,
                            Utils.extractByteArrayFromBody(response));
                }
            }
            
            if (Utils.statusCodeMatches(response.statusCode(), "4XX")) {
                // no content
                throw new APIException(
                        response,
                        response.statusCode(),
                        "API error occurred",
                        Utils.extractByteArrayFromBody(response));
            }
            
            if (Utils.statusCodeMatches(response.statusCode(), "5XX")) {
                // no content
                throw new APIException(
                        response,
                        response.statusCode(),
                        "API error occurred",
                        Utils.extractByteArrayFromBody(response));
            }
            
            throw new APIException(
                    response,
                    response.statusCode(),
                    "Unexpected status code received: " + response.statusCode(),
                    Utils.extractByteArrayFromBody(response));
        }
    }
    public static class Async extends Base
            implements AsyncRequestOperation<GetPassageAudioRequest, io.github.walker_tx.esv.models.operations.async.GetPassageAudioResponse> {

        public Async(SDKConfiguration sdkConfiguration) {
            super(sdkConfiguration);
        }

        private CompletableFuture<HttpRequest> onBuildRequest(GetPassageAudioRequest request) throws Exception {
            HttpRequest req = buildRequest(request, GetPassageAudioRequest.class);
            return this.sdkConfiguration.asyncHooks().beforeRequest(createBeforeRequestContext(), req);
        }

        private CompletableFuture<HttpResponse<Blob>> onError(HttpResponse<Blob> response, Throwable error) {
            return this.sdkConfiguration.asyncHooks().afterError(createAfterErrorContext(), response, error);
        }

        private CompletableFuture<HttpResponse<Blob>> onSuccess(HttpResponse<Blob> response) {
            return this.sdkConfiguration.asyncHooks().afterSuccess(createAfterSuccessContext(), response);
        }

        @Override
        public CompletableFuture<HttpResponse<Blob>> doRequest(GetPassageAudioRequest request) {
            return Exceptions.unchecked(() -> onBuildRequest(request)).get().thenCompose(client::sendAsync)
                    .handle((resp, err) -> {
                        if (err != null) {
                            return onError(null, err);
                        }
                        if (Utils.statusCodeMatches(resp.statusCode(), "400", "401", "4XX", "5XX")) {
                            return onError(resp, null);
                        }
                        return CompletableFuture.completedFuture(resp);
                    })
                    .thenCompose(Function.identity())
                    .thenCompose(this::onSuccess);
        }

        @Override
        public CompletableFuture<io.github.walker_tx.esv.models.operations.async.GetPassageAudioResponse> handleResponse(
                HttpResponse<Blob> response) {
            String contentType = response
                    .headers()
                    .firstValue("Content-Type")
                    .orElse("application/octet-stream");
            io.github.walker_tx.esv.models.operations.async.GetPassageAudioResponse.Builder resBuilder =
                    io.github.walker_tx.esv.models.operations.async.GetPassageAudioResponse
                            .builder()
                            .contentType(contentType)
                            .statusCode(response.statusCode())
                            .rawResponse(response);
            if (Utils.statusCodeMatches(response.statusCode(), "200") && Utils.contentTypeMatches(contentType, "audio/mpeg")) {
                resBuilder.responseStream(response.body());
            }

            io.github.walker_tx.esv.models.operations.async.GetPassageAudioResponse res = resBuilder.build();
            
            if (Utils.statusCodeMatches(response.statusCode(), "200")) {
                if (Utils.contentTypeMatches(contentType, "audio/mpeg")) {
                    return CompletableFuture.completedFuture(res);
                } else {
                    return Utils.createAsyncApiError(response, "Unexpected content-type received: " + contentType);
                }
            }
            
            if (Utils.statusCodeMatches(response.statusCode(), "400", "401")) {
                if (Utils.contentTypeMatches(contentType, "application/json")) {
                    return response.body().toByteArray().thenApply(bodyBytes -> {
                        io.github.walker_tx.esv.models.errors.async.Error out;
                        try {
                            out = Utils.mapper().readValue(
                                    bodyBytes,
                                    new TypeReference<>() {
                                    });
                        } catch (Exception e) {
                            throw new RuntimeException(e);
                        }
                        throw out;
                    });
                } else {
                    return Utils.createAsyncApiError(response, "Unexpected content-type received: " + contentType);
                }
            }
            
            if (Utils.statusCodeMatches(response.statusCode(), "4XX")) {
                // no content
                return Utils.createAsyncApiError(response, "API error occurred");
            }
            
            if (Utils.statusCodeMatches(response.statusCode(), "5XX")) {
                // no content
                return Utils.createAsyncApiError(response, "API error occurred");
            }
            
            return Utils.createAsyncApiError(response, "Unexpected status code received: " + response.statusCode());
        }
    }
}
