/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package io.github.walker_tx.esv.models.operations.async;

import static io.github.walker_tx.esv.operations.Operations.AsyncRequestOperation;

import io.github.walker_tx.esv.SDKConfiguration;
import io.github.walker_tx.esv.models.operations.GetPassageHtmlRequest;
import io.github.walker_tx.esv.operations.GetPassageHtml;
import io.github.walker_tx.esv.utils.Utils;
import java.lang.Exception;
import java.util.concurrent.CompletableFuture;

public class GetPassageHtmlRequestBuilder {

    private GetPassageHtmlRequest request;
    private final SDKConfiguration sdkConfiguration;

    public GetPassageHtmlRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public GetPassageHtmlRequestBuilder request(GetPassageHtmlRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public CompletableFuture<GetPassageHtmlResponse> call() throws Exception {
        
        AsyncRequestOperation<GetPassageHtmlRequest, GetPassageHtmlResponse> operation
              = new GetPassageHtml.Async(sdkConfiguration);

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }
}
