/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package io.github.walker_tx.esv.utils;
import io.github.walker_tx.esv.utils.Blob;
import java.net.http.HttpResponse;

public interface AsyncResponse {
    
    /**
     * Returns the value of the Content-Type header.
     **/
    String contentType();
    
    /** 
     * Returns the HTTP status code.
     **/
    int statusCode();
    
    /**
     * Returns the raw response.
     **/
    HttpResponse<Blob> rawResponse();
}