/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package io.github.walker_tx.esv.utils;

public final class Constants {

    public static final boolean HAS_CLIENT_CREDENTIALS_BASIC = false;

}