/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package io.github.walker_tx.esv.utils;

/**
 * Implemented by classes that have security annotations on fields.
 **/
public interface HasSecurity {
}