/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package io.github.walker_tx.esv.models.operations;

import io.github.walker_tx.esv.utils.Utils;

public class GetPassageTextRequestBuilder {

    private GetPassageTextRequest request;
    private final SDKMethodInterfaces.MethodCallGetPassageText sdk;

    public GetPassageTextRequestBuilder(SDKMethodInterfaces.MethodCallGetPassageText sdk) {
        this.sdk = sdk;
    }

    public GetPassageTextRequestBuilder request(GetPassageTextRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public GetPassageTextResponse call() throws Exception {

        return sdk.getText(
            request);
    }
}
