/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package io.github.walker_tx.esv.models.operations;

import static io.github.walker_tx.esv.operations.Operations.RequestOperation;

import io.github.walker_tx.esv.SDKConfiguration;
import io.github.walker_tx.esv.operations.GetPassageHtml;
import io.github.walker_tx.esv.utils.Utils;
import java.lang.Exception;

public class GetPassageHtmlRequestBuilder {

    private GetPassageHtmlRequest request;
    private final SDKConfiguration sdkConfiguration;

    public GetPassageHtmlRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public GetPassageHtmlRequestBuilder request(GetPassageHtmlRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public GetPassageHtmlResponse call() throws Exception {
        
        RequestOperation<GetPassageHtmlRequest, GetPassageHtmlResponse> operation
              = new GetPassageHtml.Sync(sdkConfiguration);

        return operation.handleResponse(operation.doRequest(request));
    }
}
