/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package io.github.walker_tx.esv.models.operations;

import io.github.walker_tx.esv.utils.Utils;
import java.lang.Exception;
import java.lang.String;

public class GetPassageAudioRequestBuilder {

    private String query;
    private final SDKMethodInterfaces.MethodCallGetPassageAudio sdk;

    public GetPassageAudioRequestBuilder(SDKMethodInterfaces.MethodCallGetPassageAudio sdk) {
        this.sdk = sdk;
    }

    public GetPassageAudioRequestBuilder query(String query) {
        Utils.checkNotNull(query, "query");
        this.query = query;
        return this;
    }

    public GetPassageAudioResponse call() throws Exception {

        return sdk.getAudio(
            query);
    }
}
