/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package io.github.walker_tx.esv.models.operations;

import static io.github.walker_tx.esv.operations.Operations.RequestOperation;

import io.github.walker_tx.esv.SDKConfiguration;
import io.github.walker_tx.esv.operations.GetPassageTextOperation;
import io.github.walker_tx.esv.utils.Utils;
import java.lang.Exception;

public class GetPassageTextRequestBuilder {

    private GetPassageTextRequest request;
    private final SDKConfiguration sdkConfiguration;

    public GetPassageTextRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public GetPassageTextRequestBuilder request(GetPassageTextRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public GetPassageTextResponse call() throws Exception {
        
        RequestOperation<GetPassageTextRequest, GetPassageTextResponse> operation
              = new GetPassageTextOperation( sdkConfiguration);

        return operation.handleResponse(operation.doRequest(request));
    }
}
