workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Esv-OAS:
        inputs:
            - location: registry.speakeasyapi.dev/walker/esv/esv-org-api:main
        overlays:
            - location: overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/walker/esv/esv-oas
targets:
    esv:
        target: java
        source: Esv-OAS
        publish:
            java:
                ossrhUsername: $ossrh_username
                ossrhPassword: $ossrh_password
                gpgSecretKey: $java_gpg_secret_key
                gpgPassPhrase: $java_gpg_passphrase
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/walker/esv/esv-oas-java-code-samples
            labelOverride:
                fixedValue: Java (SDK)
            blocking: false
