/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package io.github.walker_tx.esv;

import static io.github.walker_tx.esv.operations.Operations.AsyncRequestOperation;

import io.github.walker_tx.esv.models.operations.GetPassageAudioRequest;
import io.github.walker_tx.esv.models.operations.GetPassageHtmlRequest;
import io.github.walker_tx.esv.models.operations.GetPassageTextRequest;
import io.github.walker_tx.esv.models.operations.SearchPassagesRequest;
import io.github.walker_tx.esv.models.operations.async.GetPassageAudioRequestBuilder;
import io.github.walker_tx.esv.models.operations.async.GetPassageAudioResponse;
import io.github.walker_tx.esv.models.operations.async.GetPassageHtmlRequestBuilder;
import io.github.walker_tx.esv.models.operations.async.GetPassageHtmlResponse;
import io.github.walker_tx.esv.models.operations.async.GetPassageTextRequestBuilder;
import io.github.walker_tx.esv.models.operations.async.GetPassageTextResponse;
import io.github.walker_tx.esv.models.operations.async.SearchPassagesRequestBuilder;
import io.github.walker_tx.esv.models.operations.async.SearchPassagesResponse;
import io.github.walker_tx.esv.operations.GetPassageAudio;
import io.github.walker_tx.esv.operations.GetPassageHtml;
import io.github.walker_tx.esv.operations.GetPassageText;
import io.github.walker_tx.esv.operations.SearchPassages;
import java.lang.String;
import java.util.concurrent.CompletableFuture;


public class AsyncPassages {
    private final SDKConfiguration sdkConfiguration;
    private final Passages syncSDK;

    AsyncPassages(Passages syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public Passages sync() {
        return syncSDK;
    }


    /**
     * Get Bible passage HTML
     * 
     * <p>Returns Bible passage text with HTML formatting
     * 
     * <p>https://api.esv.org/docs/passage-html/ - Esv.org API Docs for `/v3/passages/html`
     * 
     * @return The async call builder
     */
    public GetPassageHtmlRequestBuilder getHtml() {
        return new GetPassageHtmlRequestBuilder(sdkConfiguration);
    }

    /**
     * Get Bible passage HTML
     * 
     * <p>Returns Bible passage text with HTML formatting
     * 
     * <p>https://api.esv.org/docs/passage-html/ - Esv.org API Docs for `/v3/passages/html`
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return CompletableFuture&lt;GetPassageHtmlResponse&gt; - The async response
     */
    public CompletableFuture<GetPassageHtmlResponse> getHtml(GetPassageHtmlRequest request) {
        AsyncRequestOperation<GetPassageHtmlRequest, GetPassageHtmlResponse> operation
              = new GetPassageHtml.Async(sdkConfiguration);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Search Bible passages
     * 
     * <p>Returns search results for Bible passages based on the provided query
     * 
     * <p>https://api.esv.org/docs/passage-search/ - Esv.org API Docs for `/v3/passage/search`
     * 
     * @return The async call builder
     */
    public SearchPassagesRequestBuilder search() {
        return new SearchPassagesRequestBuilder(sdkConfiguration);
    }

    /**
     * Search Bible passages
     * 
     * <p>Returns search results for Bible passages based on the provided query
     * 
     * <p>https://api.esv.org/docs/passage-search/ - Esv.org API Docs for `/v3/passage/search`
     * 
     * @param query The text to search for
     * @param pageSize Number of results to return per page
     * @param page Page number to return
     * @return CompletableFuture&lt;SearchPassagesResponse&gt; - The async response
     */
    public CompletableFuture<SearchPassagesResponse> search(
            String query, long pageSize,
            long page) {
        SearchPassagesRequest request =
            SearchPassagesRequest
                .builder()
                .query(query)
                .pageSize(pageSize)
                .page(page)
                .build();
        AsyncRequestOperation<SearchPassagesRequest, SearchPassagesResponse> operation
              = new SearchPassages.Async(sdkConfiguration);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Get Bible passage audio
     * 
     * <p>Returns audio file for Bible passages based on the provided query
     * 
     * <p>https://api.esv.org/docs/passage-audio/ - Esv.org API Docs for `/v3/passage/audio`
     * 
     * @return The async call builder
     */
    public GetPassageAudioRequestBuilder getAudio() {
        return new GetPassageAudioRequestBuilder(sdkConfiguration);
    }

    /**
     * Get Bible passage audio
     * 
     * <p>Returns audio file for Bible passages based on the provided query
     * 
     * <p>https://api.esv.org/docs/passage-audio/ - Esv.org API Docs for `/v3/passage/audio`
     * 
     * @param query Bible passage reference (e.g., "John 3:16" or "43011016")
     * @return CompletableFuture&lt;GetPassageAudioResponse&gt; - The async response
     */
    public CompletableFuture<GetPassageAudioResponse> getAudio(String query) {
        GetPassageAudioRequest request =
            GetPassageAudioRequest
                .builder()
                .query(query)
                .build();
        AsyncRequestOperation<GetPassageAudioRequest, GetPassageAudioResponse> operation
              = new GetPassageAudio.Async(sdkConfiguration);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Get Bible passage text
     * 
     * <p>Returns Bible passage text based on the provided query parameters
     * 
     * <p>https://api.esv.org/docs/passage-text/ - Esv.org API Docs for `/v3/passages/text`
     * 
     * @return The async call builder
     */
    public GetPassageTextRequestBuilder getText() {
        return new GetPassageTextRequestBuilder(sdkConfiguration);
    }

    /**
     * Get Bible passage text
     * 
     * <p>Returns Bible passage text based on the provided query parameters
     * 
     * <p>https://api.esv.org/docs/passage-text/ - Esv.org API Docs for `/v3/passages/text`
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return CompletableFuture&lt;GetPassageTextResponse&gt; - The async response
     */
    public CompletableFuture<GetPassageTextResponse> getText(GetPassageTextRequest request) {
        AsyncRequestOperation<GetPassageTextRequest, GetPassageTextResponse> operation
              = new GetPassageText.Async(sdkConfiguration);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
