/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package io.github.walker_tx.esv;
/**
 * ESV.org API: A convenient way to fetch content from ESV.org.
 * 
 * <p>The ESV API provides access to the ESV text, with a customizable presentation in  multiple formats.
 * 
 * <p>https://api.esv.org/ - ESV API Website
 */
public class AsyncEsv {

    private final AsyncPassages passages;

    public AsyncPassages passages() {
        return passages;
    }

    private final SDKConfiguration sdkConfiguration;
    private final Esv syncSDK;

    AsyncEsv(Esv syncSDK, SDKConfiguration sdkConfiguration) {
        this.syncSDK = syncSDK;
        this.sdkConfiguration = sdkConfiguration;
        this.passages = new AsyncPassages(syncSDK.passages(), sdkConfiguration);
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public Esv sync() {
        return syncSDK;
    }
}
