/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package io.github.walker_tx.esv.models.errors;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.github.walker_tx.esv.utils.Utils;
import java.lang.Object;
import java.lang.Override;
import java.lang.RuntimeException;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Map;
import java.util.Optional;


@SuppressWarnings("serial")
public class Error extends RuntimeException {

    @JsonProperty("code")
    private String code;


    @JsonProperty("message")
    private String message;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("details")
    private Optional<? extends Map<String, Object>> details;

    @JsonCreator
    public Error(
            @JsonProperty("code") String code,
            @JsonProperty("message") String message,
            @JsonProperty("details") Optional<? extends Map<String, Object>> details) {
        super("API error occurred");
        Utils.checkNotNull(code, "code");
        Utils.checkNotNull(message, "message");
        Utils.checkNotNull(details, "details");
        this.code = code;
        this.message = message;
        this.details = details;
    }
    
    public Error(
            String code,
            String message) {
        this(code, message, Optional.empty());
    }

    @JsonIgnore
    public String code() {
        return code;
    }

    @JsonIgnore
    public String message() {
        return message;
    }

    @JsonIgnore
    @Override
    public String getMessage() {
        return Utils.valueOrNull(message);
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<Map<String, Object>> details() {
        return (Optional<Map<String, Object>>) details;
    }

    public static Builder builder() {
        return new Builder();
    }


    public Error withCode(String code) {
        Utils.checkNotNull(code, "code");
        this.code = code;
        return this;
    }

    public Error withMessage(String message) {
        Utils.checkNotNull(message, "message");
        this.message = message;
        return this;
    }

    public Error withDetails(Map<String, Object> details) {
        Utils.checkNotNull(details, "details");
        this.details = Optional.ofNullable(details);
        return this;
    }


    public Error withDetails(Optional<? extends Map<String, Object>> details) {
        Utils.checkNotNull(details, "details");
        this.details = details;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Error other = (Error) o;
        return 
            Utils.enhancedDeepEquals(this.code, other.code) &&
            Utils.enhancedDeepEquals(this.message, other.message) &&
            Utils.enhancedDeepEquals(this.details, other.details);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            code, message, details);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Error.class,
                "code", code,
                "message", message,
                "details", details);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String code;

        private String message;

        private Optional<? extends Map<String, Object>> details = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        public Builder code(String code) {
            Utils.checkNotNull(code, "code");
            this.code = code;
            return this;
        }


        public Builder message(String message) {
            Utils.checkNotNull(message, "message");
            this.message = message;
            return this;
        }


        public Builder details(Map<String, Object> details) {
            Utils.checkNotNull(details, "details");
            this.details = Optional.ofNullable(details);
            return this;
        }

        public Builder details(Optional<? extends Map<String, Object>> details) {
            Utils.checkNotNull(details, "details");
            this.details = details;
            return this;
        }

        public Error build() {

            return new Error(
                code, message, details);
        }

    }
}

