/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package dev.walkertx.esv.models.operations;

import dev.walkertx.esv.utils.Utils;

public class GetPassageHtmlRequestBuilder {

    private GetPassageHtmlRequest request;
    private final SDKMethodInterfaces.MethodCallGetPassageHtml sdk;

    public GetPassageHtmlRequestBuilder(SDKMethodInterfaces.MethodCallGetPassageHtml sdk) {
        this.sdk = sdk;
    }

    public GetPassageHtmlRequestBuilder request(GetPassageHtmlRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public GetPassageHtmlResponse call() throws Exception {

        return sdk.getHtml(
            request);
    }
}
