/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */


package dev.walkertx.esv.models.operations;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
/**
 * IndentUsing - Character to use for indentation
 */
public enum IndentUsing {
    SPACE("space"),
    TAB("tab");

    @JsonValue
    private final String value;

    private IndentUsing(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<IndentUsing> fromValue(String value) {
        for (IndentUsing o: IndentUsing.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}
