/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package dev.walkertx.esv.models.operations;

import java.lang.Exception;
import java.lang.String;

public class SDKMethodInterfaces {


    public interface MethodCallGetPassageHtml {
        GetPassageHtmlResponse getHtml(
            GetPassageHtmlRequest request) throws Exception;
    }


    public interface MethodCallSearchPassages {
        SearchPassagesResponse search(
            String query,
            long pageSize,
            long page) throws Exception;
    }


    public interface MethodCallGetPassageAudio {
        GetPassageAudioResponse getAudio(
            String query) throws Exception;
    }


    public interface MethodCallGetPassageText {
        GetPassageTextResponse getText(
            GetPassageTextRequest request) throws Exception;
    }


}
